### ISSUE TITLE
import pyTFM plugin fails 

### ISSUE THREAD

**Issue by alexlib** [fabrylab/clickpoints#18]
On Python 3.10 (Windows 10, miniconda3)

```
import TFM_addon.TFM_addon
Traceback (most recent call last):
  File "C:\Users\alex\miniconda3\envs\pytfm\lib\site-packages\clickpoints\modules\ScriptLauncher.py", line 420, in add_script
    self.script_launcher.activateScript(self.selected_script)
  File "C:\Users\alex\miniconda3\envs\pytfm\lib\site-packages\clickpoints\modules\ScriptLauncher.py", line 501, in activateScript
    if script.activate(self, silent=silent):
  File "C:\Users\alex\miniconda3\envs\pytfm\lib\site-packages\clickpoints\modules\ScriptLauncher.py", line 230, in activate
    raise err
  File "C:\Users\alex\miniconda3\envs\pytfm\lib\site-packages\clickpoints\modules\ScriptLauncher.py", line 224, in activate
    self.addon_module = import_module(folder + "." + basefilename)
  File "C:\Users\alex\miniconda3\envs\pytfm\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\alex\miniconda3\envs\pytfm\lib\site-packages\pyTFM\TFM_addon\TFM_addon.py", line 4, in <module>
    from pyTFM.TFM_functions_for_clickpoints import *  # must be on top because of some matplotlib backend issues
  File "C:\Users\alex\miniconda3\envs\pytfm\lib\site-packages\pyTFM\TFM_functions_for_clickpoints.py", line 10, in <module>
    from pyTFM.frame_shift_correction import *
  File "C:\Users\alex\miniconda3\envs\pytfm\lib\site-packages\pyTFM\frame_shift_correction.py", line 12, in <module>
    from skimage.feature import register_translation
ImportError: cannot import name 'register_translation' from 'skimage.feature' (C:\Users\alex\miniconda3\envs\pytfm\lib\site-packages\skimage\feature\__init__.py)
```

**Comment by alexlib** [comment]
On Python 3.7 the installation fails with another message

```
(pytfm) PS C:\Users\alex> clickpoints
args ['C:\\Users\\alex\\miniconda3\\envs\\pytfm\\Scripts\\clickpoints']
ClickPoints 1.9.10
Using Python 3.7.12 final 64bit
Using PyQt5 5.15.6
C:\Users\alex\miniconda3\envs\pytfm\lib\site-packages\_distutils_hack\__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "C:\Users\alex\miniconda3\envs\pytfm\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\alex\miniconda3\envs\pytfm\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\alex\miniconda3\envs\pytfm\Scripts\clickpoints.exe\__main__.py", line 7, in <module>
  File "C:\Users\alex\miniconda3\envs\pytfm\lib\site-packages\clickpoints\launch.py", line 78, in main
    from clickpoints.Core import ClickPointsWindow
  File "C:\Users\alex\miniconda3\envs\pytfm\lib\site-packages\clickpoints\Core.py", line 54, in <module>
    from clickpoints.modules.Timeline import Timeline
  File "C:\Users\alex\miniconda3\envs\pytfm\lib\site-packages\clickpoints\modules\Timeline.py", line 34, in <module>
    from quamash import QEventLoop
ModuleNotFoundError: No module named 'quamash'
Press any key to continue . . .
```

**Comment by alexlib** [comment]
> On Python 3.10 (Windows 10, miniconda3)
> 
> ```
> import TFM_addon.TFM_addon
> Traceback (most recent call last):
>   File "C:\Users\alex\miniconda3\envs\pytfm\lib\site-packages\clickpoints\modules\ScriptLauncher.py", line 420, in add_script
>     self.script_launcher.activateScript(self.selected_script)
>   File "C:\Users\alex\miniconda3\envs\pytfm\lib\site-packages\clickpoints\modules\ScriptLauncher.py", line 501, in activateScript
>     if script.activate(self, silent=silent):
>   File "C:\Users\alex\miniconda3\envs\pytfm\lib\site-packages\clickpoints\modules\ScriptLauncher.py", line 230, in activate
>     raise err
>   File "C:\Users\alex\miniconda3\envs\pytfm\lib\site-packages\clickpoints\modules\ScriptLauncher.py", line 224, in activate
>     self.addon_module = import_module(folder + "." + basefilename)
>   File "C:\Users\alex\miniconda3\envs\pytfm\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "C:\Users\alex\miniconda3\envs\pytfm\lib\site-packages\pyTFM\TFM_addon\TFM_addon.py", line 4, in <module>
>     from pyTFM.TFM_functions_for_clickpoints import *  # must be on top because of some matplotlib backend issues
>   File "C:\Users\alex\miniconda3\envs\pytfm\lib\site-packages\pyTFM\TFM_functions_for_clickpoints.py", line 10, in <module>
>     from pyTFM.frame_shift_correction import *
>   File "C:\Users\alex\miniconda3\envs\pytfm\lib\site-packages\pyTFM\frame_shift_correction.py", line 12, in <module>
>     from skimage.feature import register_translation
> ImportError: cannot import name 'register_translation' from 'skimage.feature' (C:\Users\alex\miniconda3\envs\pytfm\lib\site-packages\skimage\feature\__init__.py)
> ```

see 
https://scikit-image.org/docs/0.19.x/release_notes.html#api-changes
in 0.19.1 the register_translation is removed 


The deprecated skimage.feature.masked_register_translation function has been removed (use skimage.registration.phase_cross_correlation instead).

**Comment by alexlib** [comment]
please remove those lines 

https://github.com/fabrylab/pyTFM/search?q=register_translation

since it fails the pyTFM plugin loading into clickpoints

**Comment by rgerum** [comment]
The new function was already used, but the import of register_translation was still present. I removed the import.
You can update to the current github version with:
pip install git+https://github.com/fabrylab/pyTFM --upgrade

The quamash problem with clickpoints was also fixed in december, you can update to the github version with:
pip install git+https://github.com/fabrylab/clickpoints/ --upgrade

**Comment by alexlib** [comment]
I see you closed the issue, but I still experience issues with the installation, both on Windows 10 and on WSL under Windows 10  - using the commands you suggested. 

```
(pytfm) alex@DESKTOP-OV3L1FT:/mnt/c/Users/alex$ clickpoints
args ['/home/alex/anaconda3/envs/pytfm/bin/clickpoints']
ClickPoints 1.9.10
Using Python 3.10.2 final 64bit
Using PyQt5 5.15.6
/home/alex/anaconda3/envs/pytfm/lib/python3.10/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "/home/alex/anaconda3/envs/pytfm/bin/clickpoints", line 8, in <module>
    sys.exit(main())
  File "/home/alex/anaconda3/envs/pytfm/lib/python3.10/site-packages/clickpoints/launch.py", line 78, in main
    from clickpoints.Core import ClickPointsWindow
  File "/home/alex/anaconda3/envs/pytfm/lib/python3.10/site-packages/clickpoints/Core.py", line 54, in <module>
    from clickpoints.modules.Timeline import Timeline
  File "/home/alex/anaconda3/envs/pytfm/lib/python3.10/site-packages/clickpoints/modules/Timeline.py", line 34, in <module>
    from quamash import QEventLoop
ModuleNotFoundError: No module named 'quamash'
```

when I manually add quamash by 

` pip install quamash `

I end up with 

```
(pytfm) alex@DESKTOP-OV3L1FT:/mnt/c/Users/alex$ clickpoints
args ['/home/alex/anaconda3/envs/pytfm/bin/clickpoints']
ClickPoints 1.9.10
Using Python 3.10.2 final 64bit
Using PyQt5 5.15.6
/home/alex/anaconda3/envs/pytfm/lib/python3.10/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "/home/alex/anaconda3/envs/pytfm/bin/clickpoints", line 8, in <module>
    sys.exit(main())
  File "/home/alex/anaconda3/envs/pytfm/lib/python3.10/site-packages/clickpoints/launch.py", line 78, in main
    from clickpoints.Core import ClickPointsWindow
  File "/home/alex/anaconda3/envs/pytfm/lib/python3.10/site-packages/clickpoints/Core.py", line 54, in <module>
    from clickpoints.modules.Timeline import Timeline
  File "/home/alex/anaconda3/envs/pytfm/lib/python3.10/site-packages/clickpoints/modules/Timeline.py", line 34, in <module>
    from quamash import QEventLoop
  File "/home/alex/anaconda3/envs/pytfm/lib/python3.10/site-packages/quamash/__init__.py", line 594, in <module>
    from ._unix import _SelectorEventLoop
  File "/home/alex/anaconda3/envs/pytfm/lib/python3.10/site-packages/quamash/_unix.py", line 44, in <module>
    class _SelectorMapping(collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'
```

**Comment by alexlib** [comment]
@rgerum 
https://github.com/harvimt/quamash/commit/d9520f44ee19701769178bfa8b02bfd7b9904f78

**Comment by rgerum** [comment]
Hmm strange, clickpoints should not use quamash at all. It should use qasync instead.
So this line that is referenced in your error message is in the repository
from qasync import QEventLoop
So maybe you did not execute the pip install command in the right virtual environment? Or it did not get installed properly. I should make a new release to have this problem fixed for people installing it over pypi.

**Comment by alexlib** [comment]
i'm repeating the installation for the 5th time, removing and creating a new environment every time. things get wrong in a different way if I install first clickpoints -> stuck at a new error 
```
(pytfm) PS C:\Users\alex> clickpoints
args ['C:\\Users\\alex\\miniconda3\\envs\\pytfm\\Scripts\\clickpoints']
ClickPoints 1.9.10
Using Python 3.10.2 final 64bit
Using PyQt5 5.15.6
C:\Users\alex\miniconda3\envs\pytfm\lib\site-packages\_distutils_hack\__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
LoadConfig ['C:\\Users\\alex\\miniconda3\\envs\\pytfm\\Scripts\\clickpoints']  False
Traceback (most recent call last):
  File "C:\Users\alex\miniconda3\envs\pytfm\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\alex\miniconda3\envs\pytfm\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\alex\miniconda3\envs\pytfm\Scripts\clickpoints.exe\__main__.py", line 7, in <module>
  File "C:\Users\alex\miniconda3\envs\pytfm\lib\site-packages\clickpoints\launch.py", line 102, in main
    window = ClickPointsWindow(config, app)
  File "C:\Users\alex\miniconda3\envs\pytfm\lib\site-packages\clickpoints\Core.py", line 112, in __init__
    self.move(x, y*0.5)
TypeError: arguments did not match any overloaded call:
  move(self, QPoint): argument 1 has unexpected type 'float'
  move(self, int, int): argument 1 has unexpected type 'float'
```

or if I start from pyTFM (that installs clickpoints from pypi probably) and then get to the errors I reported above.

**Comment by rgerum** [comment]
Ok this is a bug that has also been recently fixed.
I now made a new release. So hopefully it should now be installed correctly over pypi.

**Comment by alexlib** [comment]
@rgerum please note that there is some difference in the way pip implements the requirements if someone installs it through pyTFM or through clickpoints. What I mean is that if I start with 

`pip install git+https://github.com/fabrylab/clickpoints`
or 
`pip install git+https://github.com/fabrylab/pytfm`

I end up with different errors. Probably it requires somewhat more precise version instructions to pip.

**Comment by rgerum** [comment]
well i guess that by installing pytfm with pip and git it installs the pypi clickpoint version, which should now work as I made a release. But if you have any suggestions on what I can improve to make the installation process easier, I am happy to hear that.
